export type MenuItem = {
  code?: string;
  name: string;
  viName?: string;
  description?: string;
  price: string;
};

export type MenuCategory = {
  name: string;
  viName?: string;
  note?: string;
  items: MenuItem[];
};

export const menu: MenuCategory[] = [
  {
    name: "Beef Soup with Rice Noodle",
    viName: "Phở",
    items: [
      { code: "1", name: "Special Combo", viName: "Phở Đặc Biệt", description: "Slices of steak, flank, fatty brisket, tendon, tripe & beef meatballs (large).", price: "17.50" },
      { code: "2", name: "Oxtail", viName: "Phở Đuôi Bò", price: "17.99" },
      { code: "3", name: "Filet Mignon", viName: "Phở Filet Mignon", price: "17.50" },
      { code: "4", name: "Shrimp", viName: "Phở Tôm", price: "16.99" },
      { code: "5", name: "Seafood Combination", viName: "Phở Đồ Biển", description: "Shrimp, squid, fish balls & imitation crab.", price: "16.99" },
      { code: "6", name: "Shredded Chicken", viName: "Phở Gà", price: "15.99" },
      { code: "7", name: "Slices of Steak", viName: "Phở Tái", price: "15.99" },
      { code: "8", name: "Slices of Steak & Flank", viName: "Phở Tái Nạm", price: "15.99" },
      { code: "8", name: "Slices of Steak & Tendon", viName: "Phở Tái Gân", price: "15.99" },
      { code: "8", name: "Slices of Steak, Flank & Fatty Brisket", viName: "Phở Tái Nạm Gầu", price: "15.99" },
      { code: "8", name: "Slices of Steak & Lean Meat", viName: "Phở Tái Chín", price: "15.99" },
      { code: "8", name: "Slices of Steak, Flank & Tripe", viName: "Phở Tái Nạm Sách", price: "15.99" },
      { code: "8", name: "Slices of Steak & Beef Meatballs", viName: "Phở Tái Bò Viên", price: "15.99" },
      { code: "8", name: "Slices of Steak, Flank & Beef Meatballs", viName: "Phở Tái Nạm Bò Viên", price: "15.99" },
      { code: "8", name: "Slices of Steak & Tripe", viName: "Phở Tái Sách", price: "15.99" },
      { code: "8", name: "Slices of Steak, Flank & Tendon", viName: "Phở Tái Nạm Gân", price: "15.99" },
      { code: "10", name: "Beef Meatballs", viName: "Phở Bò Viên", price: "15.99" },
      { code: "11", name: "Rice Noodle Soup No Meat", viName: "Phở Bánh Nước", price: "12.00" },
      { name: "Back Rib Pho", price: "18.50" },
    ],
  },
  {
    name: "Vermicelli in Broth",
    viName: "Bún Nước",
    items: [
      { code: "17", name: "Large Round Vermicelli", viName: "Bún Bò Huế", description: "With beef shank, pork ham, pork leg & pork blood in spicy soup.", price: "16.99" },
    ],
  },
  {
    name: "Specialty Soup with Rice or Egg Noodle",
    viName: "Hủ Tíu Hoặc Mì",
    items: [
      { code: "12", name: "Crispy Chicken Leg Quarter", viName: "Hủ Tíu Hoặc Mì Đùi Gà Chiên Dòn", description: "Broth on the side.", price: "16.00" },
      { code: "13", name: "Quail Eggs, Pork Heart, Pork & Shrimp", viName: "Hủ Tíu Hoặc Mì Mỹ Tho", price: "16.99" },
      { code: "14", name: "Wonton & B.B.Q. Pork", viName: "Hủ Tíu Hoặc Mì Hoành Thánh Xá Xíu", description: "Wonton and BBQ pork in a savory broth, choice of rice or egg noodle.", price: "16.99" },
      { code: "15", name: "Seafood Combination", viName: "Hủ Tíu Hoặc Mì Đồ Biển", price: "16.99" },
      { code: "16", name: "Beef Stew", viName: "Hủ Tíu Hoặc Mì Bò Kho", description: "Tender beef pieces in a rich, savory broth, choice of rice or egg noodle.", price: "16.99" },
    ],
  },
  {
    name: "Udon Soup Vietnamese Style",
    viName: "Bánh Canh",
    items: [
      { code: "21", name: "Fish Fillet", viName: "Bánh Canh Cá", price: "16.99" },
      { code: "21", name: "Shredded Chicken", viName: "Bánh Canh Gà", price: "16.99" },
      { code: "21", name: "Shrimp Fillet", viName: "Bánh Canh Tôm", price: "16.99" },
      { code: "21", name: "Seafood Combination", viName: "Bánh Canh Đồ Biển", price: "16.99" },
    ],
  },
  {
    name: "Vermicelli",
    viName: "Bún",
    items: [
      { code: "25", name: "Grilled Meat, Pork", viName: "Bún Thịt Nướng Heo", price: "16.50" },
      { code: "25", name: "Grilled Meat, Chicken", viName: "Bún Thịt Nướng Gà", price: "16.50" },
      { code: "25", name: "Grilled Meat, Beef", viName: "Bún Thịt Nướng Bò", price: "16.50" },
      { code: "26", name: "Shredded Pork, Grilled Pork & Egg Roll", viName: "Bún Bì Thịt Nướng Chả Giò", description: "May be substituted with chicken or beef.", price: "16.99" },
      { code: "27", name: "Grilled Shrimp, Pork & Egg Roll", viName: "Bún Tôm Thịt Nướng Chả Giò", description: "May be substituted with chicken or beef.", price: "17.50" },
      { code: "28", name: "Grilled Pork & Bean Curd Shrimp Cake", viName: "Bún Thịt Nướng Tàu Hủ Ky", description: "May be substituted with chicken or beef.", price: "17.99" },
      { code: "28", name: "Grilled Pork & Shrimp Paste on Sugar Cane", viName: "Bún Thịt Nướng & Chạo Tôm", description: "May be substituted with chicken or beef.", price: "17.99" },
      { code: "29", name: "Grilled Pork, Shrimp Paste on Sugar Cane & Shrimp Cake", viName: "Bún Thịt Nướng, Chạo Tôm & Tàu Hủ Ky", description: "May be substituted with chicken or beef.", price: "19.99" },
      { code: "30", name: "Sautéed Beef with Lemongrass", viName: "Bún Bò Xào Xả Ớt", price: "17.00" },
      { code: "30", name: "Sautéed Chicken with Lemongrass", viName: "Bún Gà Xào Xả Ớt", price: "17.00" },
    ],
  },
  {
    name: "Steamed or Broken Rice",
    viName: "Cơm Hoặc Cơm Tấm",
    items: [
      { code: "31", name: "Crispy Chicken Leg Quarter", viName: "Cơm Đùi Gà Chiên Dòn", price: "16.50" },
      { code: "32", name: "Grilled Meat, Pork", viName: "Cơm Thịt Nướng Heo", price: "16.50" },
      { code: "32", name: "Grilled Meat, Chicken", viName: "Cơm Thịt Nướng Gà", price: "16.50" },
      { code: "32", name: "Grilled Meat, Beef", viName: "Cơm Thịt Nướng Bò", price: "16.50" },
      { code: "32", name: "Grilled Pork Chop", viName: "Cơm Thịt Nướng Sườn", price: "16.50" },
      { code: "33", name: "Shredded Pork, Egg Cake & Grilled Pork", viName: "Cơm Bì Chả Thịt Nướng", description: "May be substituted with chicken or beef.", price: "18.00" },
      { code: "33", name: "Shredded Pork, Egg Cake & Pork Chop", viName: "Cơm Bì Chả Sườn Nướng", description: "May be substituted with chicken or beef.", price: "18.00" },
      { code: "34", name: "Grilled Pork with Shrimp Paste on Sugar Cane", viName: "Cơm Thịt Nướng & Chạo Tôm", description: "May be substituted with chicken or beef.", price: "18.00" },
      { code: "34", name: "Pork Chop with Shrimp Paste on Sugar Cane", viName: "Cơm Sườn Nướng & Chạo Tôm", description: "May be substituted with chicken or beef.", price: "18.00" },
      { code: "34", name: "Grilled Pork with Bean Curd Shrimp Cake", viName: "Cơm Thịt Nướng & Tàu Hủ Ky", description: "May be substituted with chicken or beef.", price: "18.00" },
      { code: "34", name: "Pork Chop with Bean Curd Shrimp Cake", viName: "Cơm Sườn Nướng & Tàu Hủ Ky", description: "May be substituted with chicken or beef.", price: "18.00" },
      { code: "35", name: "Shredded Pork, Grilled Pork, Egg Cake, Egg Roll & Shrimp Cake", viName: "Cơm Bì Chả Thịt Nướng Chả Giò Tàu Hủ Ky", description: "May be substituted with chicken or beef.", price: "20.50" },
      { code: "35", name: "Shredded Pork, Grilled Pork, Egg Cake, Egg Roll & Shrimp Paste on Sugar Cane", viName: "Cơm Bì Chả Thịt Nướng Chả Giò Chạo Tôm", description: "May be substituted with chicken or beef.", price: "20.50" },
      { code: "36", name: "Korean B.B.Q. Short Ribs", viName: "Cơm Sườn Bò Đại Hàn", description: "Vietnamese-style Korean BBQ short ribs, steamed or broken rice.", price: "18.00" },
      { code: "37", name: "Spicy Chicken Sautéed with Lemongrass & Onions", viName: "Cơm Gà Xào Xả Ớt", price: "17.00" },
      { code: "38", name: "Sautéed Shrimp, Chicken with Broccoli", viName: "Cơm Tôm Gà Xào Bông Cải", price: "17.00" },
      { code: "39", name: "Orange Chicken with Bell Pepper, Carrots & Onions", viName: "Cơm Orange Chicken", price: "17.50" },
      { code: "40", name: "Red Fried Rice with Roasted Cornish Hen & Fried Egg", viName: "Cơm Gà Rô-Ti ½ Con", description: "Red fried rice with a roasted cornish hen half and a fried egg, choice of steamed or broken rice.", price: "17.50" },
      { code: "41", name: "Diced Filet Mignon with Onions", viName: "Cơm Bò Lúc Lắc", description: "French style, diced filet mignon, onions, choice of steamed or broken rice.", price: "20.50" },
    ],
  },
  {
    name: "Fried Rice",
    viName: "Cơm Chiên",
    items: [
      { code: "42", name: "Chicken", viName: "Cơm Chiên Gà", price: "16.50" },
      { code: "42", name: "Beef", viName: "Cơm Chiên Bò", price: "16.50" },
      { code: "42", name: "Shrimp", viName: "Cơm Chiên Tôm", price: "17.50" },
      { code: "42", name: "B.B.Q. Pork and Chinese Sausage", viName: "Cơm Chiên Xá Xíu Và Lạp Xưởng", description: "Fried rice with BBQ pork and Chinese sausage, egg, peas, carrots & onions.", price: "16.50" },
      { code: "43", name: "Combination of Shrimp, Beef, Chicken", viName: "Cơm Chiên Thập Cẩm", price: "17.25" },
      { code: "44", name: "Seafood Combination", viName: "Cơm Chiên Đồ Biển", description: "Shrimp, squid, fish balls & imitation crab.", price: "17.25" },
      { code: "45", name: "Fried Rice with No Meat", viName: "Cơm Chiên Không Thịt", price: "12.50" },
    ],
  },
  {
    name: "Pan-Fried & Stir-Fried Dishes",
    viName: "Hủ Tíu / Mì Xào",
    items: [
      { code: "46", name: "Pan-Fried Rice Noodles, Combination & Mixed Vegetables", viName: "Phở Áp Chảo (Bánh Nhỏ)", description: "Small noodles.", price: "18.00" },
      { code: "46", name: "Pan-Fried Rice Noodles, Seafood & Mixed Vegetables", viName: "Phở Áp Chảo Đồ Biển (Bánh Nhỏ)", description: "Small noodles.", price: "18.00" },
      { code: "46", name: "Stir-Fried Rice Noodles, Combination & Mixed Vegetables", viName: "Hủ Tíu Xào Đồ Biển (Bánh Nhỏ)", description: "Small noodles.", price: "18.00" },
      { code: "47", name: "Pan-Fried Rice Noodles, Combination & Mixed Vegetables", viName: "Phở Áp Chảo (Bánh Lớn)", description: "Big flat noodles.", price: "18.00" },
      { code: "47", name: "Pan-Fried Rice Noodles, Seafood & Mixed Vegetables", viName: "Phở Áp Chảo Đồ Biển (Bánh Lớn)", description: "Big flat noodles.", price: "18.00" },
      { code: "47", name: "Stir-Fried Rice Noodles, Seafood & Mixed Vegetables", viName: "Hủ Tíu Xào Đồ Biển (Bánh Lớn)", description: "Big flat noodles.", price: "18.00" },
      { code: "48", name: "Stir-Fried Egg Noodles, Combination & Mixed Vegetables", viName: "Mì Xào Thập Cẩm", description: "Soft or crispy noodles.", price: "18.00" },
      { code: "48", name: "Stir-Fried Egg Noodles, Seafood & Mixed Vegetables", viName: "Mì Xào Đồ Biển", description: "Soft or crispy noodles.", price: "18.00" },
      { code: "49", name: "Stir-Fried Rice Noodles with Combination", viName: "Hủ Tíu Xào Lá Quế Thập Cẩm", description: "With basil, bell peppers, jalapeño, carrots, celery & Chinese broccoli.", price: "18.00" },
      { code: "49", name: "Stir-Fried Rice Noodles with Seafood", viName: "Hủ Tíu Xào Lá Quế Đồ Biển", description: "With basil, bell peppers, jalapeño, carrots, celery & Chinese broccoli.", price: "18.00" },
      { code: "50", name: "Stir-Fried Udon in Basil Sauce", viName: "Bánh Canh Nhật Xào", description: "Chinese broccoli, bell pepper & jalapeño, choice of beef or chicken.", price: "18.00" },
      { code: "50", name: "Stir-Fried Udon with Seafood", viName: "Bánh Canh Nhật Xào Đồ Biển", description: "In basil sauce with Chinese broccoli, bell pepper & jalapeño.", price: "18.00" },
      { code: "51", name: "Beef Pasta", viName: "Nui Xào Bò", description: "Stir-fried pasta with beef, onions, scallions & bell pepper, choice of beef or chicken.", price: "18.00" },
      { code: "53", name: "Pad Thai", viName: "Hủ Tíu Xào Kiểu Thái", description: "Stir-fried rice noodles with egg, shrimp, chicken, bean sprouts, green onion, carrots & crushed peanuts.", price: "17.50" },
    ],
  },
  {
    name: "French Bread Sandwich",
    viName: "Bánh Mì",
    items: [
      { code: "56", name: "Grilled Pork, Chicken or Beef Sandwich", viName: "Bánh Mì Heo, Gà Nướng", price: "9.75" },
      { code: "56", name: "Grilled Pork, Beef Sandwich", viName: "Bánh Mì Heo, Bò Nướng", price: "9.75" },
      { code: "57", name: "Special Combination", viName: "Bánh Mì Đặc Biệt", description: "Roasted pork, pork pâté, and pâté.", price: "9.75" },
      { code: "16", name: "Beef Stew", viName: "Bánh Mì Bò Kho", description: "Served in a bowl.", price: "16.99" },
    ],
  },
  {
    name: "Salad",
    viName: "Xà Lách",
    items: [
      { code: "S-2", name: "Grilled Chicken", viName: "Xà Lách Gà Nướng", price: "14.50" },
      { code: "S-3", name: "Sautéed Beef", viName: "Xà Lách Bò Xào", price: "14.50" },
    ],
  },
  {
    name: "Appetizers",
    viName: "Món Khai Vị",
    items: [
      { code: "A-1", name: "Egg Rolls", viName: "Chả Giò", description: "2 or 4 rolls.", price: "6.50" },
      { code: "A-2", name: "Shrimp & Pork Spring Rolls", viName: "Gỏi Cuốn", description: "2 or 4 rolls.", price: "7.99" },
      { code: "A-3", name: "Grilled Pork Paste Rolls", viName: "Nem Nướng Cuốn", description: "2 or 4 rolls.", price: "8.50" },
      { code: "A-4", name: "Crispy Fish Rolls", description: "2 or 4 rolls.", price: "8.50" },
      { code: "A-7", name: "Chicken Strips", description: "Served with house special creamy sauce, 6–8 pieces.", price: "14.00" },
      { code: "A-8", name: "House Special Chicken Wings", viName: "Cánh Gà Chiên Dòn", price: "15.00" },
      { code: "A-10", name: "Fried Cream Cheese Wontons", viName: "Hoành Thánh Cheese", description: "8 pieces.", price: "11.50" },
      { code: "A-11", name: "Fried Chicken Wontons", viName: "Hoành Thánh Gà", description: "8 pieces.", price: "11.50" },
      { code: "A-13", name: "Fried Calamari", viName: "Mực Chiên Dòn", price: "14.50" },
    ],
  },
  {
    name: "Vegetarian",
    viName: "Món Chay",
    items: [
      { code: "9", name: "Noodle Soup and Vegetables", viName: "Phở Chay", description: "Choice of vegan or beef broth.", price: "15.99" },
      { code: "30", name: "Vermicelli with Sautéed Fried Tofu", viName: "Bún Xào Chay", description: "Lemongrass & onions.", price: "17.00" },
      { code: "37", name: "Sautéed Fried Tofu", viName: "Cơm Đậu Hủ Xào Xả Ớt", description: "Lemongrass & onions with steamed rice.", price: "17.00" },
      { code: "42", name: "Fried Rice", viName: "Cơm Chiên Chay", description: "With veggie meat and egg.", price: "16.50" },
      { code: "46", name: "Pan-Fried Rice Noodles", viName: "Phở Áp Chảo", description: "Broccoli, baby bok choy, carrots, celery, baby corn & onions, small noodles.", price: "18.00" },
      { code: "47", name: "Pan-Fried Rice Noodles", viName: "Phở Áp Chảo", description: "Broccoli, baby bok choy, carrots, celery, baby corn & onions, big flat noodles.", price: "18.00" },
      { code: "46", name: "Stir-Fried Rice Noodles", viName: "Hủ Tíu Xào Chay", description: "Small noodles.", price: "18.00" },
      { code: "47", name: "Stir-Fried Rice Noodles", viName: "Hủ Tíu Xào Chay", description: "Big flat noodles.", price: "18.00" },
      { code: "48", name: "Stir-Fried Egg Noodles", viName: "Mì Xào Chay", description: "Soft or crispy noodles.", price: "18.00" },
      { code: "49", name: "Stir-Fried Rice Noodles", viName: "Hủ Tíu Xào Lá Quế", description: "Bell peppers, jalapeño, basil, carrots, celery & Chinese broccoli.", price: "18.00" },
      { code: "50", name: "Stir-Fried Udon Noodle in Basil Sauce", viName: "Bánh Canh Nhật Xào Lá Quế", description: "Bean sprouts, Chinese broccoli, bell peppers & jalapeño.", price: "18.00" },
      { code: "56", name: "Veggie Sandwich", viName: "Bánh Mì Chay", description: "Mayonnaise, cucumber, tomato, pickled daikon & carrots, cilantro & jalapeño.", price: "9.75" },
      { code: "A-1", name: "Veggie Egg Rolls", viName: "Chả Giò Chay", price: "6.25" },
      { code: "A-2", name: "Veggie Spring Rolls", viName: "Gỏi Cuốn Chay", description: "Fried tofu stir with shiitake mushrooms and lemongrass.", price: "7.99" },
    ],
  },
  {
    name: "Beverages",
    viName: "Giải Khát",
    items: [
      { name: "Iced Tea", viName: "Trà Đá", description: "Refreshing jasmine tea, steeped and crisp.", price: "2.50" },
      { name: "Vietnamese Iced Coffee", description: "Hot or iced, with condensed milk.", price: "6.25" },
      { name: "Thai Iced Tea", viName: "Trà Thái", description: "Rich, creamy blend of thai tea and milk, ice or chewy boba pearls.", price: "5.50" },
      { name: "Iced Milk Tea", viName: "Trà Sữa", description: "Original, strawberry, taro, honeydew, green apple, or hazelnut.", price: "6.50" },
      { name: "Iced Tea Lemonade", viName: "Trà Đá Chanh Đường", description: "Iced tea and lemonade, gentle bitterness meets zesty sweetness.", price: "5.25" },
      { name: "Fresh Squeezed Lemonade", viName: "Đá Chanh", description: "Original, strawberry, raspberry, peach, mango, or pomegranate.", price: "5.25" },
      { name: "Lemonade Soda", viName: "Soda Chanh", description: "Original, strawberry, raspberry, peach, mango, or pomegranate.", price: "5.25" },
      { name: "Soft Drinks", viName: "Nước Ngọt", description: "Coke, Diet Coke, Sprite, Dr. Pepper, Fanta orange, Fuze raspberry iced tea.", price: "3.50" },
      { name: "Coconut Juice", viName: "Nước Dừa", price: "6.25" },
    ],
  },
  {
    name: "Soup Add-ons",
    items: [
      { name: "Steak", description: "Slices of rare steak for pho.", price: "4.75" },
      { name: "Filet Mignon", description: "Slices of filet mignon for pho.", price: "6.25" },
      { name: "Flank", description: "Slices of flank steak for pho.", price: "4.25" },
      { name: "Fatty Brisket", description: "Slices of fatty brisket for pho.", price: "4.25" },
      { name: "Lean Meat", description: "Slices of lean brisket for pho.", price: "4.25" },
      { name: "Tendon", description: "Beef tendon for pho.", price: "4.25" },
      { name: "Tripe", description: "Tripe for pho.", price: "4.25" },
      { name: "Beef Meatball", description: "Beef meatball for pho.", price: "3.25" },
      { name: "Shrimp", description: "3 pieces of steamed shrimp.", price: "3.75" },
      { name: "Wontons", description: "3 pieces steamed wontons.", price: "3.75" },
      { name: "Squid", description: "Steamed squid.", price: "4.25" },
      { name: "Fish Fillet", price: "3.50" },
      { name: "Steamed Fish Balls", price: "4.25" },
      { name: "Imitation Crab Meat", price: "4.25" },
      { name: "Quail Eggs", description: "4 pieces.", price: "2.50" },
      { name: "Vinegar Onions", description: "Sliced onions dressed with vinegar.", price: "1.50" },
      { name: "Steamed Vegetables", description: "Broccoli, bok choy, carrots & cabbage.", price: "4.25" },
      { name: "Rice Noodle", price: "3.25" },
      { name: "Egg Noodles", price: "3.50" },
      { name: "Medium Sized Broth", price: "3.25" },
      { name: "Large Sized Broth", price: "5.50" },
    ],
  },
  {
    name: "Extras / Add-ons",
    items: [
      { name: "Grilled Beef", price: "6.50" },
      { name: "Grilled Chicken", price: "6.50" },
      { name: "Grilled Pork", price: "6.50" },
      { name: "Diced Filet Mignon", price: "14.25" },
      { name: "Orange Chicken", price: "11.25" },
      { name: "Roasted Cornish Hen", price: "10.75" },
      { name: "Fried Chicken Leg Quarter", price: "5.25" },
      { name: "Chinese Sausage", price: "4.00" },
      { name: "Egg Cake", price: "4.25" },
      { name: "Fried Egg", price: "1.99" },
      { name: "French Roll Bread", price: "1.99" },
      { name: "Steamed Rice", price: "3.50" },
      { name: "Brown Rice", price: "3.00" },
    ],
  },
];
